services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: camagru_app
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www/html
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=camagru
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: camagru_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: camagru
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql
  adminer:
      image: adminer
      ports:
        - 8081:8080
volumes:
  db_data: