version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: camagru_app
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www/html
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=camagru
    depends_on:
      - db
      - mailhog

  db:
    image: mysql:8.0
    container_name: camagru_db
    platform: linux/arm64/v8  # Ajoutez cette ligne si nécessaire
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: camagru
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: camagru_adminer
    platform: linux/arm64/v8  # Ajoutez cette ligne si nécessaire
    ports:
      - "8081:8080"

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    platform: linux/amd64  # Spécifiez la plateforme ici
    ports:
      - "8025:8025"   # Interface web de MailHog
      - "1025:1025"   # Port SMTP

volumes:
  db_data:
